# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Filebt = QtWidgets.QPushButton(self.centralwidget)
        self.Filebt.setGeometry(QtCore.QRect(30, 310, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Filebt.setFont(font)
        self.Filebt.setCheckable(False)
        self.Filebt.setAutoRepeat(False)
        self.Filebt.setObjectName("Filebt")
        self.Input = QtWidgets.QTextEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(30, 20, 361, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Input.setFont(font)
        self.Input.setObjectName("Input")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 300, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.inrbt = QtWidgets.QRadioButton(self.groupBox)
        self.inrbt.setGeometry(QtCore.QRect(20, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.inrbt.setFont(font)
        self.inrbt.setChecked(False)
        self.inrbt.setObjectName("inrbt")
        self.bbrbt = QtWidgets.QRadioButton(self.groupBox)
        self.bbrbt.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.bbrbt.setFont(font)
        self.bbrbt.setChecked(True)
        self.bbrbt.setObjectName("bbrbt")
        self.Logo_text = QtWidgets.QTextEdit(self.centralwidget)
        self.Logo_text.setGeometry(QtCore.QRect(30, 450, 741, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Logo_text.setFont(font)
        self.Logo_text.setReadOnly(True)
        self.Logo_text.setObjectName("Logo_text")
        self.Output = QtWidgets.QTextEdit(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(410, 20, 361, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Output.setFont(font)
        self.Output.setReadOnly(True)
        self.Output.setObjectName("Output")
        self.DoItbt = QtWidgets.QPushButton(self.centralwidget)
        self.DoItbt.setGeometry(QtCore.QRect(590, 320, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.DoItbt.setFont(font)
        self.DoItbt.setObjectName("DoItbt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Filebt.setText(_translate("MainWindow", "Загрузить массив из файла"))
        self.groupBox.setTitle(_translate("MainWindow", "Вид сортировки"))
        self.inrbt.setText(_translate("MainWindow", "Вставкой"))
        self.bbrbt.setText(_translate("MainWindow", "Пузырьковая"))
        self.DoItbt.setText(_translate("MainWindow", "Выполнить"))
